line-length = 120

extend-select = [
    "ASYNC",
    "UP",
    "I",
    "B",
    "ICN",
    "F",
    "RET",
    "SIM",
    "PTH",
    "TRY",
    "NPY",
    "PERF",
    "RUF",
    "PIE",
    "C4",
]
fixable = ["ALL"]

extend-ignore = ["F401"]
