line-length = 120

extend-select = [
  "A",
  "ASYNC",
  "UP",
  "I",
  "B",
  "ICN",
  "F",
  "RET",
  "SIM",
  "TRY",
  "NPY",
  "PERF",
  "RUF",
  "PIE",
  "C4",
]
fixable = ["ALL"]

extend-ignore = ["F401", "E501"]

# Ignore `E402` (import violations) in all `__init__.py` files
[per-file-ignores]
"__init__.py" = ["E402"]
