line-length = 120

extend-select = [
    "ASYNC",
    "UP",
    "I",
    "F",
    "N",
    "RET",
    "SIM",
    "PTH",
    "TRY",
    "NPY",
    "PERF",
    "RUF",
    "PIE",
    "C4",
]
fixable = ["ALL"]
