input_folder = "/home/xpsyc/Documents/HiddenStuff/LineArt/source/" # the input folder to convert
scale = 4                                                          # the scale to compare with and convert into lrs
extension = "webp"                                                 # the extension which to convert to
extensions = "webp,png,jpg"                                        # the extensions to search for

# modifiers
recursive = false     # whether to keep folders, or to replace them with underscores. ex false: relative/path/to/file.png -> relative_path_to_file.png
convert_spaces = true # whether to convert spaces into underscores. ex: relative path/to file.png -> relative_path/to_file.png
threads = 9           # how many threads to use during multiprocessing pools.
chunksize = 5         # the number of files to use in the imap scenario. smaller is supposedly slower so I decided to bring this up to the user to decide
# limit = 1000          # the max number of files to find, or to use.
limit_mode = "before" # before|after
simulate = false      # just ends before actually converting.
purge = false         # purges the files that relate to files in the input
purge_all = false     # purges all the files in the output
make_lr = false       # whether or not to make a folder for lowres output
overwrite = false     # disables checking if the files already exist in the output
verbose = false       # prints data the database picked up during population while it converts files
sort_by = "path"      # sorts the files after filtering, based on the gathered data

# filters
# whitelist = ""       # strings that need to be in the input files
# blacklist = ""       # strings that CANNOT be in the input files
list_separator = "," # the separator that splits the whitelist and blacklist and extensions
minsize = 128        # the minimum size an image must be
# maxsize = 4096       # the maximum size an image can be
crop_mod = true
before = "2016" # will only use images where the modified time is before 2016
# after = "2010" # will only use images where the modifiedtime is after 2010
hash_images = true         # hash the images using imagehash, then eliminate visually similar images
hash_choice = "ignore_all" # ignore_all|newest|oldest|size
hash_mode = "average"      # average|crop_resistant|color|dhash|dhash_vertical|phash|phash_simple|whash|whash-db4
