save_interval = 60
chunksize = 100
filepath = "filedb.feather"


[stats]
before = "2100"
after = "1980"

[resolution]
min = 0
max = 2048
crop = false
scale = 4

[hashing]
resolver = "ignore_all"      # ignore_all | column name
include_only_partial = false # only takes in account the part of the dataframe given
hasher = "average"           #average | color | crop_resistant | dhash | dhash_vertical | phash | phash_simple | whash | whash_db4
[channels]
min_channels = 1
max_channels = 4

[blackwhitelists]
whitelist = []
blacklist = []
exclusive = false

[limit]
total = 1000
