save_interval = 60
chunksize = 100
filepath = "filedb.feather"

[stats]
before = "2100" #Only get items before this threshold
after = "1980"  #Only get items after this threshold
[resolution]
min = 128
max = 4096
crop = true #checks if valid after a slight crop
scale = 4
[hashing]
resolver = "ignore_all" # ignore_all | column name
hasher = "average"      #average | color | crop_resistant | dhash | dhash_vertical | phash | phash_simple | whash | whash_db4
[channels]
min_channels = 4
max_channels = 4
[blackwhitelists]
whitelist = []
blackist = []
exclusive = false #Only allow files that are valid by every whitelist string
[limit]
total = 1000
