trim = true
trim_age_limit_secs = 604800
trim_check_exists = true
save_interval_secs = 60
chunksize = 600
filepath = "filedb.feather"

[stats]
before = "2100" #Only get items before this threshold
after = "1980"  #Only get items after this threshold
[resolution]
min = 0
max = 2048
crop = false #if true, then it will check if it is valid after cropping a little to be divisible by scale
scale = 4
[hashing]
hasher = "average"      #average | color | crop_resistant | dhash | dhash_vertical | phash | phash_simple | whash | whash_db4
resolver = "ignore_all" #ignore_all | newest | oldest | size
[channels]
min_channels = 1
max_channels = 4

[blackwhitelists]
whitelist = []
blackist = []
exclusive = false #Only allow files that are valid by every whitelist string
